services:
  db:
    image: mysql:8.0
    container_name: tokoloka_dev_db
    environment:
      MYSQL_ROOT_PASSWORD: "!Password2024"
      MYSQL_DATABASE: tokoloka
      MYSQL_USER: user
      MYSQL_PASSWORD: "!Password2024"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: golang:1.23
    container_name: tokoloka_dev_app
    working_dir: /app
    volumes:
      - .:/app
    command: ["sh", "-c", "go run main.go"]
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=AS12wbasb12iw!asdubaf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tokoloka_dev_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: "!Password2024"
    ports:
      - "8081:80"
    volumes:
      - ./apache-config.conf:/etc/apache2/conf-enabled/servername.conf

volumes:
  db_data:




